Repository Learning-Is-Vital-In-Development/24-optimizing-java-2, pull requests merged in 2024-01, with the labels that each got.

#1 init: initial setting
  README.md
  ch02/README.md
  ch03/README.md
  ch04/README.md
  ch05/README.md
  ch06/README.md
  ch07/README.md
  ch08/README.md
  ch09/README.md
  ch10/README.md
  ch11/README.md
  ch12/README.md
  ch13/README.md
  ch14/README.md
Labels: size/M

#2 github setting
  .github/CODEOWNERS
  .github/workflows/pr_auto_merge.yaml
Labels: size/XS

#6 1주차 PR
  ch02/yoojeong.md
  ch03/yoojeong.md
Labels: size/L

#7 1주차 PR
  ch02/youngji.md
  ch03/youngji.md
Labels: size/L

#9 1주차 PR
  ch02/lsj8367.md
  ch03/lsj8367.md
Labels: size/L

#8 1주차 PR
  ch02/doxxx.md
  ch03/doxxx.md
  ch03/img.png
  ch03/img_1.png
Labels: size/L

#5 1주차 PR
  ch02/youjin.md
  ch03/youjin.md
Labels: size/L

#4 1주차 pr
  ch02/5uhwann.md
  ch03/5uhwann.md
Labels: size/M

#16 2 주 차~
  ch04/doxxx.md
Labels: size/M

#14 2주차 PR
  ch04/5uhwann.md
Labels: size/M

#12 2주차 PR, Readme week1 추가
  README.md
  ch04/youjin.md
Labels: size/L

#11 2주차 PR
  ch04/yoojeong.md
Labels: size/M

#10 2주차 PR
  ch04/seungjae.md
Labels: size/L

#3 1주차 pr입니다.
  ch02/박시창.md
  ch03/박시창.md
  ch04/박시창.md
Labels: size/L

#22 3주차 PR
  ch05/youngji.md
Labels: size/L

#20 3주차 정리
  ch05/lsj8367.md
Labels: size/L

#19 Youjin-Chapter5
  ch05/youjin.md
Labels: size/L

#18 3주차 정리
  README.md
  ch05/5uhwann.md
Labels: size/M
