Repository Learning-Is-Vital-In-Development/24-optimizing-java-2, pull requests merged in 2024-02, with the labels that each got.

#17 3주차 입니다!
  ch05/박시창.md
Labels: size/M

#24 4주차 pr입니다.
  ch06/5uhwann.md
  ch07/5uhwann.md
Labels: size/L

#27 5,6주차 PR
  ch06/lsj8367.md
  ch07/lsj8367.md
Labels: size/L

#32 5uhwann - Chapter8
  ch08/5uhwann.md
Labels: size/M

#31 ch 8
  ch08/doxxx.md
Labels: size/S

#30 SeungJae - Chapter8
  ch08/lsj8367.md
Labels: size/L

#28 Youjin - Chapter8
  ch08/youjin0201.md
Labels: size/L
